import { expect, test } from '@playwright/test'

test('workspace persistence: manage, compare, integrity, export, and continue', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('query-template-select')).toBeVisible()

  await page.getByTestId('query-template-select').selectOption('macro_outlook')

  await page.getByTestId('query-input').fill('What does the current yield curve shape imply for equities over the next 6 months?')
  await page.getByTestId('query-input').press('Enter')

  await expect(page.getByTestId('brief-complete')).toBeVisible({ timeout: 30000 })
  await expect(page.getByTestId('brief-template-title')).toContainText('Macro outlook')
  await page.getByTestId('claim-link-bull-1-inversion-easing').click()
  await expect(page.getByTestId('evidence-drilldown')).toBeVisible()
  await expect(page.getByTestId('source-state-label-0')).toBeVisible()

  await page.getByTestId('save-session-button').click()
  await expect(page.getByTestId('workspace-status')).toContainText('Saved session', { timeout: 15000 })
  await expect(page.getByTestId('workspace-item-0')).toBeVisible()
  await expect(page.getByTestId('workspace-evaluation-0')).toBeVisible()
  await expect(page.getByTestId('workspace-snapshot-0')).toBeVisible()
  await expect(page.getByTestId('workspace-state-labels-0')).toBeVisible()
  await expect(page.getByTestId('workspace-live-metadata-0')).toBeVisible()

  await page.getByTestId('query-template-select').selectOption('thesis_change_compare')
  await page.getByTestId('query-input').fill('Continue from this session with an event-probability perspective.')
  await page.getByTestId('query-input').press('Enter')

  await expect(page.getByTestId('brief-complete')).toBeVisible({ timeout: 30000 })
  await expect(page.getByTestId('brief-template-title')).toContainText('Compare old vs new thesis')
  await page.getByTestId('save-session-button').click()
  await expect(page.getByTestId('workspace-item-1')).toBeVisible({ timeout: 15000 })

  await page.getByTestId('workspace-collection-create-title').fill('Yield Curve Notebook')
  await page.getByTestId('workspace-collection-create-summary').fill('Threaded research sessions')
  await page.getByTestId('workspace-collection-create-submit').click()
  await expect(page.getByTestId('workspace-collection-detail')).toBeVisible({ timeout: 10000 })

  await page.getByTestId('workspace-collection-add-active-session').click()
  await expect(page.getByTestId('workspace-collection-timeline-item-0')).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('workspace-collection-thesis-0')).toBeVisible()
  await expect(page.getByTestId('workspace-collection-delta-0')).toBeVisible()
  await expect(page.getByTestId('workspace-collection-timeline-signature')).toBeVisible()

  await page.getByTestId('workspace-reopen-1').click()
  await expect(page.getByTestId('brief-complete')).toBeVisible({ timeout: 10000 })
  await page.getByTestId('workspace-collection-add-active-session').click()
  await expect(page.getByTestId('workspace-collection-timeline-item-1')).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('workspace-collection-delta-1')).toBeVisible()

  await page.getByTestId('workspace-collection-move-up-1').click()
  await expect(page.getByTestId('workspace-collection-reopen-0')).toBeVisible()
  await page.getByTestId('workspace-collection-reopen-0').click()
  await expect(page.getByTestId('brief-complete')).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('workspace-thread-signature')).toBeVisible()
  await expect(page.getByTestId('workspace-thread-timeline-item-0')).toBeVisible()
  await expect(page.getByTestId('workspace-thread-delta-0')).toBeVisible()
  await page.getByTestId('workspace-collection-export-bundle').click()
  await expect(page.getByTestId('workspace-status')).toContainText('Exported collection', { timeout: 10000 })
  await page.getByTestId('workspace-thread-reopen-0').click()
  await expect(page.getByTestId('brief-complete')).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('trace-step-0')).toBeVisible()
  await expect(page.getByTestId('source-list')).toBeVisible()
  await expect(page.getByTestId('snapshot-summary')).toBeVisible()

  const sessionIds = await page
    .locator('[data-testid^="workspace-item-"]')
    .evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-session-id')).filter(Boolean) as string[])
  expect(sessionIds.length).toBeGreaterThanOrEqual(2)

  await page.getByTestId('workspace-compare-left').selectOption(sessionIds[0])
  await page.getByTestId('workspace-compare-right').selectOption(sessionIds[1])
  await page.getByTestId('workspace-compare-run').click()
  await expect(page.getByTestId('workspace-compare-result')).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('workspace-compare-drift-panel')).toBeVisible()
  await expect(page.getByTestId('workspace-compare-drift-snapshot-id-count')).toBeVisible()
  await expect(page.getByTestId('workspace-compare-drift-freshness-count')).toBeVisible()
  await expect(page.getByTestId('workspace-compare-drift-source-set')).toBeVisible()
  await expect(page.getByTestId('workspace-compare-drift-evaluation-signature')).toBeVisible()
  await expect(page.getByTestId('workspace-compare-conflict-panel')).toBeVisible()
  await expect(page.getByTestId('workspace-compare-conflict-worsened-count')).toBeVisible()

  await page.getByTestId('workspace-recapture-0').click()
  await expect(page.getByTestId('workspace-status')).toContainText('Recaptured', { timeout: 10000 })
  await expect(page.getByTestId('workspace-recapture-lineage')).toBeVisible()
  await expect(page.getByTestId('workspace-recapture-before-signature')).toBeVisible()
  await expect(page.getByTestId('workspace-recapture-after-signature')).toBeVisible()
  await expect(page.getByTestId('workspace-recapture-snapshot-id-changes')).toBeVisible()

  await page.getByTestId('workspace-verify-0').click()
  await expect(page.getByTestId('workspace-integrity-report')).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('workspace-integrity-provenance')).toBeVisible()
  await expect(page.getByTestId('workspace-integrity-freshness-policy')).toBeVisible()
  await expect(page.getByTestId('workspace-integrity-snapshot')).toBeVisible()
  await expect(page.getByTestId('workspace-integrity-evaluation')).toBeVisible()
  await page.getByTestId('workspace-integrity-run-all').click()
  await expect(page.getByTestId('workspace-integrity-overview')).toBeVisible({ timeout: 10000 })

  await page.getByTestId('workspace-evaluation-dashboard-run').click()
  await expect(page.getByTestId('workspace-evaluation-dashboard-result')).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('workspace-evaluation-dashboard-summary')).toBeVisible()
  await expect(page.getByTestId('workspace-evaluation-dashboard-pass-rate')).toBeVisible()
  await expect(page.getByTestId('workspace-evaluation-dashboard-signature')).toBeVisible()
  await expect(page.getByTestId('workspace-evaluation-dashboard-export-ready')).toBeVisible()

  await page.getByTestId('workspace-review-0').click()
  await expect(page.getByTestId('workspace-review-result')).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('workspace-review-status')).toContainText('PASS')
  await expect(page.getByTestId('workspace-review-item-0')).toBeVisible()

  await page.getByTestId('workspace-reopen-0').click()
  await expect(page.getByTestId('brief-complete')).toBeVisible({ timeout: 10000 })
  await page.getByTestId('workspace-review-active').click()
  await expect(page.getByTestId('workspace-review-result')).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('snapshot-summary')).toBeVisible()
  await expect(page.getByTestId('trace-step-0')).toBeVisible()
  await page.locator('[data-testid^="claim-link-"]').first().click()
  await expect(page.getByTestId('active-claim-id')).toBeVisible()
  await expect(page.getByTestId('source-preview-0')).toBeVisible()
  await expect(page.getByTestId('source-state-label-detail-0')).toBeVisible()
  await expect(page.getByTestId('source-snapshot-id-0')).toBeVisible()

  await page.getByTestId('workspace-export-current-json').click()
  await expect(page.getByTestId('workspace-status')).toContainText('Exported', { timeout: 10000 })
  await page.getByTestId('workspace-export-current-markdown').click()
  await expect(page.getByTestId('workspace-status')).toContainText('Exported', { timeout: 10000 })
  await page.getByTestId('workspace-export-current-bundle').click()
  await expect(page.getByTestId('workspace-status')).toContainText('bundle', { timeout: 10000 })

  await page.getByTestId('query-input').fill('Continue from this saved thread with a risk-off interpretation.')
  await page.getByTestId('query-input').press('Enter')

  await expect(page.getByTestId('brief-complete')).toBeVisible({ timeout: 30000 })
  await expect(page.getByTestId('query-session-hint')).toBeVisible()
  await expect(page.getByTestId('brief-followup-context')).toBeVisible()
})
